const mockData = {
  maxPage: 5,
  rooms: [
    {
      currentMembers: 3,
      maxMembers: 4,
      isWaiting: true,
      roomId: 101,
      roomName: "그냥 아무나 환영한다",
      isPrivate: true,
    },
    {
      currentMembers: 2,
      maxMembers: 4,
      isWaiting: true,
      roomId: 102,
      roomName: "이길수 없을거야 아마두",
      isPrivate: false,
    },
    {
      currentMembers: 4,
      maxMembers: 4,
      isWaiting: false,
      roomId: 103,
      roomName: "지면 100대 맞는거다",
      isPrivate: true,
    },
    {
      currentMembers: 2,
      maxMembers: 4,
      isWaiting: true,
      roomId: 104,
      roomName: "초보자던 고수던 아무나 다 와바",
      isPrivate: false,
    },
    {
      currentMembers: 4,
      maxMembers: 4,
      isWaiting: false,
      roomId: 105,
      roomName: "즐갬하실분만 아무나 환영한다",
      isPrivate: true,
    },
    {
      currentMembers: 4,
      maxMembers: 4,
      isWaiting: false,
      roomId: 106,
      roomName: "초보자분들을 위한 방",
      isPrivate: true,
    },
    {
      currentMembers: 1,
      maxMembers: 4,
      isWaiting: true,
      roomId: 107,
      roomName: "재밌는 게임방",
      isPrivate: false,
    },
    {
      currentMembers: 4,
      maxMembers: 4,
      isWaiting: false,
      roomId: 108,
      roomName: "고등어를 찾아라",
      isPrivate: true,
    },
    {
      currentMembers: 2,
      maxMembers: 4,
      isWaiting: true,
      roomId: 109,
      roomName: "최강자들의 방",
      isPrivate: false,
    },
    {
      currentMembers: 4,
      maxMembers: 4,
      isWaiting: false,
      roomId: 110,
      roomName: "아무나 환영합니다",
      isPrivate: true,
    },
    // {
    //   currentMembers: 1,
    //   maxMembers: 4,
    //   isWaiting: true,
    //   roomId: 111,
    //   roomName: "배우는 게임방",
    //   isPrivate: false,
    // },
    // {
    //   currentMembers: 3,
    //   maxMembers: 4,
    //   isWaiting: false,
    //   roomId: 112,
    //   roomName: "대전을 원하는 분들",
    //   isPrivate: true,
    // },
    // {
    //   currentMembers: 1,
    //   maxMembers: 4,
    //   isWaiting: true,
    //   roomId: 113,
    //   roomName: "난이도 상관없이 즐기세요",
    //   isPrivate: false,
    // },
    // {
    //   currentMembers: 4,
    //   maxMembers: 4,
    //   isWaiting: false,
    //   roomId: 114,
    //   roomName: "정신적인 친목방",
    //   isPrivate: true,
    // },
    // {
    //   currentMembers: 2,
    //   maxMembers: 4,
    //   isWaiting: true,
    //   roomId: 115,
    //   roomName: "우리방에서 함께해요",
    //   isPrivate: false,
    // },
  ],
};

export default mockData;
